nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "3001:3001"

node1:
    build: .
    ports:
        - "3000"
node2:
    build: .
    ports:
        - "3000"
node3:
    build: .
    ports:
        - "3000"