nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - node4:node4
        # add more nodes to scale up
    ports:
        - "3000:8080"

node1:
    build: ./src
    ports:
        - "3000"
node2:
    build: ./src
    ports:
        - "3000"
node3:
    build: ./src
    ports:
        - "3000"
node4:
    build: ./src
    ports:
        - "3000"
# add more nodes to scale up