#!/bin/bash

set -e
PROJECT_NAME=$(cat package.json \
  | grep name \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')

docker rmi $PROJECT_NAME-image | true
docker build -t $PROJECT_NAME-image .