#!/bin/bash

set -e
docker inspect --format '{{ .NetworkSettings.IPAddress }}' realtime-canvas-container
docker inspect --format='{{range $p, $conf := .Config.ExposedPorts}} {{$p}} {{end}}' realtime-canvas-container