#!/bin/bash

set -e

PROJECT_NAME=$(cat package.json \
  | grep name \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')

docker inspect --format '{{ .NetworkSettings.IPAddress }}' $PROJECT_NAME-container
docker inspect --format='{{range $p, $conf := .Config.ExposedPorts}} {{$p}} {{end}}' $PROJECT_NAME-container