#!/bin/bash

set -e

PROJECT_NAME=$(cat package.json \
  | grep name \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')
  
docker stop $PROJECT_NAME-container | true
docker rm $PROJECT_NAME-container | true
docker run -it --rm -p 3000:3000 --name $PROJECT_NAME-container $PROJECT_NAME-image