#!/bin/bash

set -e

PROJECT_NAME=$(cat package.json \
  | grep name \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')
  
docker run -d -p 3000:3000 --restart always --name $PROJECT_NAME-container $PROJECT_NAME-image