#!/bin/bash

set -e

PROJECT_NAME_FILE="$HOME/.dh-project-name"
read PROJECT_NAME <"$PROJECT_NAME_FILE"
  
docker stop $PROJECT_NAME-container | true
docker rm $PROJECT_NAME-container | true
docker run -it --rm -p 3000:3000 --name $PROJECT_NAME-container $PROJECT_NAME-image