nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "8080:3000"

node-docker-project-template: 
  build: . 
  ports: 
    - "3000:3000" 
  # volumes: 
  #   - .:/code 
  # links: 
  #   - other-project