#!/bin/bash

set -e

PROJECT_NAME=$(cat package.json \
  | grep name \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | tr -d '[[:space:]]')
  
DATE=`date +%Y-%m-%d`
docker logs -t --since $DATE $PROJECT_NAME-container