#!/bin/bash

set -e

PROJECT_NAME_FILE="$HOME/.dh-project-name"
read PROJECT_NAME <"$PROJECT_NAME_FILE"

docker-machine ssh $PROJECT_NAME-swarm-manager "docker swarm leave --force"
docker-machine rm $PROJECT_NAME-swarm-manager -y