#!/bin/bash

set -e

PROJECT_NAME_FILE="$HOME/.dh-project-name"
read PROJECT_NAME <"$PROJECT_NAME_FILE"

docker inspect --format '{{ .NetworkSettings.IPAddress }}' $PROJECT_NAME-container
docker inspect --format='{{range $p, $conf := .Config.ExposedPorts}} {{$p}} {{end}}' $PROJECT_NAME-container