#!/bin/bash

set -e

PROJECT_NAME_FILE="$HOME/.dh-project-name"
read PROJECT_NAME <"$PROJECT_NAME_FILE"
  
docker run -d -p 3000:3000 --restart always --name $PROJECT_NAME-container $PROJECT_NAME-image